### PR TITLE
Moved the About Us screen over to Jetpack Compose

### PR DESCRIPTION
**Pull request by Kardelio**
Addressed this issue: #57 

Here is what I did:
* Added Jetpack compose settings and dependencies to codebase
* Wrote the Composable functions copying the layout of the old xml about us fragment layout
* Added **Hilt** dependency too for Dependency Injection
* Set up the package structure for clean MVVM approach for the **About Us** screen package
* Created the `AboutUsViewModel` , `AboutUsUseCases` & `AboutUsRepository` to make the package clean MVVM and connected the pieces together
* Finally the data gathered in the ViewModel was presented to the Compose UI as Compose States and compose rendered the data
* Also added my own name to the contributor list

### CODE REVIEW

**Comment by Kardelio** [comment]
@ritwikshanker hey buddy, so I've done that work and also added Hilt and DI for the codebase and made the about us screen entirely compose now...

If you want me to go over any of it or explain any of it please let me know i would be happy to do so 👍 👍

**Review by ritwikshanker — APPROVED** [review]

**Comment by Kardelio** [comment]
Cheers @ritwikshanker , what do you think of the solution?

Also is there anything else that i can do to help out on this codebase ?

**Comment by ritwikshanker** [comment]
Yeah, @Kardelio. If you want you can pick up other screens. For example, #56 is also open. I'm also updating the APIs. So there might be a lot of [new data available to us](https://disease.sh/docs/#/). Which means more features to build. 👨🏽‍💻

**Comment by ritwikshanker** [comment]
Also, the solution was good. MVVM was done fine. As for the DI part like I said, I'm also pretty new to that, so can't say much.
The only feedback I found which we can change in the future is that to not hardcode colours and create a file like Google Sample projects have (`colors.kt`) since it eases out things and increases readability and consistency for the future.

**Pull request merged**
