### PR TITLE
#39-Add a option to select/change default country

### LINKED ISSUE #39: Add a option to select/change default country
The country which will be selected as default will always appear at the top of the list.

### PR DESCRIPTION
**Pull request by Charis1331**
Closes #39

### CODE REVIEW

**Review by ritwikshanker — APPROVED** [review]
Although this doesn't completely solves the thing I had in mind but still it's still an enhancement. Thanks 🙂

**Review by ritwikshanker — COMMENTED** [review]
This caused a major bug in the app. Now whenever the user open's the app, the country in the spinner is set to the one that is stored but the data that is being displayed is of the first element i.e. Worldwide.

**Comment by ritwikshanker** [comment]
Sorry but had to revert the changes. The issue is still assigned to you. If you want, you can still work on it. Else i'll assign it to someone else.

**Comment by Charis1331** [comment]
I see what you mean. My bad. I will update it sortly.

**Pull request merged**
